title      Arch Linux install medium (aarch64, UEFI, dtb kernel option)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/Image
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  dtb=/%INSTALL_DIR%/boot/%ARCH%/%DTB% archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% audit=0 efi=noruntime pd_ignore_unused clk_ignore_unused arm64.nopauth
